### ISSUE TITLE
Error in rocm-smi -a

### ISSUE THREAD

**Issue by BertaViader-zv** [RadeonOpenCompute/rocm_smi_lib#77]
Hello,

I have a problem with rocm-smi -a:

root@srv-0003:~/ROC-smi# ./rocm-smi -a

```
========================ROCm System Management Interface========================
Driver version: 5.6.19
================================================================================
GPU[0]          : GPU ID: 0x731f
================================================================================
================================================================================
GPU[0]          : VBIOS version: 111
================================================================================
================================================================================
GPU[0]          : Temperature (Sensor edge) (C): 67.0
GPU[0]          : Temperature (Sensor junction) (C): 76.0
GPU[0]          : Temperature (Sensor mem) (C): 68.0
================================================================================
================================================================================
GPU[0]          : dcefclk clock level: 0 (506Mhz)
GPU[0]          : fclk clock level: 1 (1085Mhz)
GPU[0]          : mclk clock level: 0 (100Mhz)
GPU[0]          : pcie clock level: 1 (16.0GT/s, x16 619Mhz)
GPU[0]          : sclk clock level: 2 (2100Mhz)
GPU[0]          : socclk clock level: 1 (1085Mhz)
================================================================================
================================================================================
GPU[0]          : Fan Level: 68 (26%)
================================================================================
================================================================================
GPU[0]          : Performance Level: auto
================================================================================
================================================================================
GPU[0]          : GPU OverDrive value (%): 0
================================================================================
================================================================================
GPU[0]          : GPU Memory OverDrive value (%): 0
================================================================================
================================================================================
GPU[0]          : Max Graphics Package Power (W): 220.0
================================================================================
================================================================================
GPU[0]          :
GPU[0]          : PROFILE_INDEX(NAME) CLOCK_TYPE(NAME) FPS MinFreqType MinActiveFreqType MinActiveFreq BoosterFreqType BoosterFreq PD_Data_limit_c PD_Data_error_coeff PD_Data_error_rate_coeff
GPU[0]          :  0 BOOTUP_DEFAULT :
GPU[0]          :                     0(       GFXCLK)       0       5       1       0       4     800 4587520  -65536       0
GPU[0]          :                     1(       SOCCLK)       0       5       1       0       3     800 1310720   -6553       0
GPU[0]          :                     2(        MEMLK)       0       5       1       0       4     800  327680  -65536       0
GPU[0]          :  1 3D_FULL_SCREEN :
GPU[0]          :                     0(       GFXCLK)       0       5       1       0       4     650 3932160   -6553  -65536
GPU[0]          :                     1(       SOCCLK)       0       5       1     850       4     800 1310720   -6553       0
GPU[0]          :                     2(        MEMLK)       0       5       4     850       4     800  327680  -65536       0
GPU[0]          :  2   POWER_SAVING :
GPU[0]          :                     0(       GFXCLK)       0       5       1       0       3       0 5898240  -65536       0
GPU[0]          :                     1(       SOCCLK)       0       5       1       0       3       0 1310720   -6553       0
GPU[0]          :                     2(        MEMLK)       0       5       1       0       3       0 1966080  -65536       0
GPU[0]          :  3          VIDEO :
GPU[0]          :                     0(       GFXCLK)       0       5       1       0       4     500 4587520  -65536       0
GPU[0]          :                     1(       SOCCLK)       0       5       1       0       4     500 1310720   -6553       0
GPU[0]          :                     2(        MEMLK)       0       5       1       0       4     500 1966080  -65536       0
GPU[0]          :  4             VR :
GPU[0]          :                     0(       GFXCLK)       0       5       4    1000       4     800 4587520  -65536       0
GPU[0]          :                     1(       SOCCLK)       0       5       1       0       4     800  327680  -65536       0
GPU[0]          :                     2(        MEMLK)       0       5       1       0       4     800  327680  -65536       0
GPU[0]          :  5        COMPUTE*:
GPU[0]          :                     0(       GFXCLK)       0       5       4    1000       3       0 3932160  -65536  -65536
GPU[0]          :                     1(       SOCCLK)       0       5       4     850       3       0  327680  -65536  -32768
GPU[0]          :                     2(        MEMLK)       0       5       4     850       3       0  327680  -65536  -32768
GPU[0]          :  6         CUSTOM :
GPU[0]          :                     0(       GFXCLK)       0       5       1       0       4     800 4587520  -65536       0
GPU[0]          :                     1(       SOCCLK)       0       5       1       0       3     800 1310720   -6553       0
GPU[0]          :                     2(        MEMLK)       0       5       1       0       4     800  327680  -65536       0
================================================================================
================================================================================
GPU[0]          : Average Graphics Package Power (W): 71.0
================================================================================
================================================================================
GPU[0]          : Supported dcefclk frequencies on GPU0
GPU[0]          : 0: 506Mhz *
GPU[0]          : 1: 886Mhz
GPU[0]          : 2: 1266Mhz
GPU[0]          :
GPU[0]          : Supported fclk frequencies on GPU0
GPU[0]          : 0: 506Mhz
GPU[0]          : 1: 1085Mhz *
GPU[0]          : 2: 1266Mhz
GPU[0]          :
GPU[0]          : Supported mclk frequencies on GPU0
GPU[0]          : 0: 100Mhz *
GPU[0]          : 1: 500Mhz
GPU[0]          : 2: 625Mhz
GPU[0]          : 3: 875Mhz
GPU[0]          :
GPU[0]          : Supported pcie frequencies on GPU0
GPU[0]          : 0: 2.5GT/s, x16 619Mhz
GPU[0]          : 1: 16.0GT/s, x16 619Mhz *
GPU[0]          :
GPU[0]          : Supported sclk frequencies on GPU0
GPU[0]          : 0: 300Mhz
GPU[0]          : 1: 1200Mhz
GPU[0]          : 2: 2100Mhz *
GPU[0]          :
GPU[0]          : Supported socclk frequencies on GPU0
GPU[0]          : 0: 506Mhz
GPU[0]          : 1: 1085Mhz *
GPU[0]          : 2: 1266Mhz
GPU[0]          :
================================================================================
================================================================================
GPU[0]          : GPU use (%): 99
================================================================================
================================================================================
GPU[0]          : GPU memory use (%): 0
================================================================================
================================================================================
GPU[0]          : GPU memory vendor: micron
================================================================================
================================================================================
GPU[0]          : PCIe Replay Count: 0
================================================================================
================================================================================
GPU[0]          : Unique ID: N/A
================================================================================
================================================================================
GPU[0]          : Serial Number: N/A
================================================================================
PIDs for KFD processes:
2683628
================================================================================
ERROR: GPU[0]           : Unable to display PowerPlay table
================================================================================
================================================================================
GPU[0]          : Voltage (mV): 1168
================================================================================
================================================================================
GPU[0]          : PCI Bus: 0000:4b:00.0
================================================================================
================================================================================
GPU[0]          : ASD firmware version:         553648188
GPU[0]          : CE firmware version:          37
GPU[0]          : DMCU firmware version:        0
GPU[0]          : MC firmware version:          0
GPU[0]          : ME firmware version:          94
GPU[0]          : MEC firmware version:         137
GPU[0]          : MEC2 firmware version:        137
GPU[0]          : PFP firmware version:         144
GPU[0]          : RLC firmware version:         128
GPU[0]          : RLC SRLC firmware version:    0
GPU[0]          : RLC SRLG firmware version:    0
GPU[0]          : RLC SRLS firmware version:    0
GPU[0]          : SDMA firmware version:        30
GPU[0]          : SDMA2 firmware version:       30
GPU[0]          : SMC firmware version:         00.42.61.00
GPU[0]          : SOS firmware version:         0x00100250
GPU[0]          : TA RAS firmware version:      00.00.00.00
GPU[0]          : TA XGMI firmware version:     00.00.00.00
GPU[0]          : UVD firmware version:         0x00000000
GPU[0]          : VCE firmware version:         0x00000000
GPU[0]          : VCN firmware version:         0x0510a00d
================================================================================
================================================================================
GPU[0]          : Card series:          Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
GPU[0]          : Card vendor:          Tul Corporation / PowerColor
GPU[0]          : 148d  DIGICOM Systems, Inc.
Traceback (most recent call last):
  File "./rocm-smi", line 3021, in <module>
    showProductName(deviceList)
  File "./rocm-smi", line 1853, in showProductName
    sku = vbios.split('-')[1][:6]
IndexError: list index out of range
```

Could you help me? I don't know if the problem is the code or the configuration, as all the configuration is in automatic mode.

Thanks,
Berta

**Comment by dmitrii-galantsev** [comment]
There was a bug with splitting strings in product names. Should be fixed now.
